version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=graphql-checkout

    ports:
      - '5432:5432'

  app:
    container_name: graphql-checkout
    image: pranotobudi/graphql-checkout:v1.0.0
    depends_on:
      - db  
    networks:
      - default
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db #as define in service name upthere
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_NAME=graphql-checkout
      - DB_SSL_MODE=disable
      - APP_ENV=development
      - PORT=8080
