// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddedProduct struct {
	UserID string `json:"user_id"`
	Sku    string `json:"sku"`
	Qty    int    `json:"qty"`
}

type CartProduct struct {
	Product              *Product `json:"product"`
	TotalItem            int      `json:"total_item"`
	TotalPricePerProduct float64  `json:"total_price_per_product"`
}

type CheckoutReport struct {
	Items      []string `json:"items"`
	TotalPrice float64  `json:"total_price"`
}

type Product struct {
	Sku          string  `json:"sku"`
	Name         string  `json:"name"`
	Price        float64 `json:"price"`
	InventoryQty int     `json:"inventory_qty"`
	PromoType    int     `json:"promo_type"`
}
