// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddedProduct struct {
	Sku string `json:"sku"`
	Qty int    `json:"qty"`
}

type CheckoutReport struct {
	Items []*ProductName `json:"items"`
	Total float64        `json:"total"`
}

type Product struct {
	Sku          string  `json:"sku"`
	Name         string  `json:"name"`
	Price        float64 `json:"price"`
	InventoryQty int     `json:"inventory_qty"`
	PromoType    int     `json:"promo_type"`
}

type ProductName struct {
	Name string `json:"name"`
}
